{% set name = "pandas-stubs" %}
{% set version = "3.0.5.260914" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pandas_stubs-{{ version }}.tar.gz
  sha256: 3f6fc1f147f68fd89c007105e7c94a948acb4ecd7eb20dc1c02e153c4ed5c250

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - types-pytz >=2022.1.1
    - numpy >=1.26.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/pandas-stubs/_typing.pyi  # [unix]
    - if not exist %SP_DIR%\\pandas-stubs\\_typing.pyi exit 1  # [win]

about:
  home: https://github.com/pandas-dev/pandas-stubs
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Collection of Pandas stub files
  description: |
    Collection of Pandas stub files supported by the pandas team
  doc_url: https://github.com/pandas-dev/pandas-stubs
  dev_url: https://github.com/pandas-dev/pandas-stubs

extra:
  recipe-maintainers:
    - twoertwein
    - Dr-Irv
