{% set name = "pandas-stubs" %}
{% set version = "1.2.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c32d489cc9d1ca3dfe8522f66337a42bc1317c0c6d294fd121bba70ad6a9744a

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - typing_extensions >=3.7.4.3  # [py<=38]
  run:
    - python
    - typing_extensions >=3.7.4.3  # [py<=38]

test:
  commands:
    - test -f $SP_DIR/pandas/py.typed  # [unix]
    - if not exist %SP_DIR%\\pandas\\py.typed exit 1  # [win]
about:
  home: https://github.com/VirtusLab/pandas-stubs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Collection of Pandas stub files
  description: |
    Collection of Pandas stub files initially generated using stubgen,
    fixed when necessary and then partially completed.
  doc_url: https://github.com/VirtusLab/pandas-stubs
  dev_url: https://github.com/VirtusLab/pandas-stubs

extra:
  recipe-maintainers:
    - zkrolikowski-vl
    - hpomorski
